server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      mvc:
        routes:
          - id: rol
            uri: lb://rol-service
            predicates:
              - Path=/api/roles/**
          - id: user
            uri: lb://user-service
            predicates:
              - Path=/api/users/**
          - id: catalogo
            uri: lb://catalogo-service
            predicates:
              - Path=/api/catalogos/**
          - id: estado
            uri: lb://estado-service
            predicates:
              - Path=/api/estados/**
          - id: libro
            uri: lb://libro-service
            predicates:
              - Path=/api/libros/**
          - id: estante
            uri: lb://estante-service
            predicates:
              - Path=/api/estantes/**
          - id: historial
            uri: lb://historial-service
            predicates:
              - Path=/api/historiales/**
          - id: multas
            uri: lb://multas-service
            predicates:
              - Path=/api/multas/**
          - id: reserva
            uri: lb://reserva-libro-service
            predicates:
              - Path=/api/reservas/**
          - id: detalle
            uri: lb://detalle-service
            predicates:
              - Path=/api/detalles/**
          - id: resena
            uri: lb://resena-libro-service
            predicates:
              - Path=/api/resenas/**

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: ${EUREKA_INSTANCE_PREFER_IP_ADDRESS:false}

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway
