spring.application.name=Libro
server.port=8085

spring.datasource.url=jdbc:mysql://localhost:3306/db_libro
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

ms.catalogo.url=http://localhost:8083
ms.estado.url=http://localhost:8084
ms.user.url=http://localhost:8082
