spring.application.name=libro-service
server.port=8085

spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/db_libro}
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASSWORD:}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

ms.catalogo.url=${MS_CATALOGO_URL:http://localhost:8083}
ms.estado.url=${MS_ESTADO_URL:http://localhost:8084}
ms.user.url=${MS_USER_URL:http://localhost:8082}

eureka.client.service-url.defaultZone=${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
eureka.instance.prefer-ip-address=${EUREKA_INSTANCE_PREFER_IP_ADDRESS:false}
eureka.instance.instance-id=${spring.application.name}