CREATE DATABASE IF NOT EXISTS db_rol
 CHARACTER SET utf8mb4 
 COLLATE utf8mb4_unicode_ci;
CREATE DATABASE IF NOT EXISTS db_user;
 CHARACTER SET utf8mb4 
 COLLATE utf8mb4_unicode_ci;
CREATE DATABASE IF NOT EXISTS db_catalogo;
 CHARACTER SET utf8mb4 
 COLLATE utf8mb4_unicode_ci;
CREATE DATABASE IF NOT EXISTS db_estado;
 CHARACTER SET utf8mb4 
 COLLATE utf8mb4_unicode_ci;
CREATE DATABASE IF NOT EXISTS db_libro;
 CHARACTER SET utf8mb4 
 COLLATE utf8mb4_unicode_ci;
CREATE DATABASE IF NOT EXISTS db_estante;
 CHARACTER SET utf8mb4 
 COLLATE utf8mb4_unicode_ci;
CREATE DATABASE IF NOT EXISTS db_historial;
 CHARACTER SET utf8mb4 
 COLLATE utf8mb4_unicode_ci;
CREATE DATABASE IF NOT EXISTS db_multas;
 CHARACTER SET utf8mb4 
 COLLATE utf8mb4_unicode_ci;
CREATE DATABASE IF NOT EXISTS db_reserva_libro;
 CHARACTER SET utf8mb4 
 COLLATE utf8mb4_unicode_ci;
CREATE DATABASE IF NOT EXISTS db_detalle;
 CHARACTER SET utf8mb4 
 COLLATE utf8mb4_unicode_ci;
CREATE DATABASE IF NOT EXISTS db_resena_libro;
 CHARACTER SET utf8mb4 
 COLLATE utf8mb4_unicode_ci;

